export const SET_NEW_DELIVERY_SERVICE = 'SET_NEW_DELIVERY_SERVICE';
export const SET_NEW_ON_SITE_SERVICE = 'SET_NEW_ON_SITE_SERVICE';
export const SET_ALL_DELIVERY_SERVICE = 'SET_ALL_DELIVERY_SERVICE';
export const SET_ALL_ON_SITE_SERVICE = 'SET_ALL_ON_SITE_SERVICE';
export const GET_EXISTING_DELIVERY_SERVICES = 'GET_EXISTING_DELIVERY_SERVICES';
export const GET_EXISTING_ON_SITE_SERVICES = 'GET_EXISTING_ON_SITE_SERVICES';