export const psycoSymps = [
  "Problemas psicológicos Agresividad",
  "Amnesia",
  "Ansiedad",
  "Ataques de Pánico",
  "Celos",
  "Depresión",
  "Duelo",
  "Estrés ",
  "Fobia",
  "TOC",
  "Trauma",
  "Adicciones Ciberadicción",
  "Alcoholismo",
  "Adicción al sexo",
  "Drogadicción",
  "Tabaquismo",
  "Ludopatía",
  "Desarrollo Personal Asertividad",
  "Habilidades sociales",
  "Inteligencia Emocional",
  "Autoestima",
  "Liderazgo",
  "Psicología Laboral Orientación vocacional",
  "Psicotécnicos",
  "Reinserción Laboral",
  "Coaching",
  "Acoso Laboral",
  "Estrés Laboral",
  "Sindrome de Burnout",
  "Otro",
  "Sexualidad Impotencia",
  "Asexual",
  "Otros",
  "Trastornos alimenticios Bulimia",
  "Anorexia",
  "Otros",
  "Terapia de pareja Convivencia",
  "Comunicación",
  "Infidelidad",
  "Sexualidad",
]
